CREATE TABLE Accounts (
    AccountID INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE Goals (
    GoalID INT IDENTITY(1,1) PRIMARY KEY,
    AccountID INT NOT NULL,
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    StartDate DATE NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID) ON DELETE CASCADE
);
GO

CREATE TABLE DailyProgress (
    ProgressID INT IDENTITY(1,1) PRIMARY KEY,
    GoalID INT NOT NULL,
    ProgressDate DATE NOT NULL,
    Status BIT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (GoalID) REFERENCES Goals(GoalID) ON DELETE CASCADE
);
GO
